# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assistantui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ASSISTANTUI(object):
    def setupUi(self, ASSISTANTUI):
        ASSISTANTUI.setObjectName("ASSISTANTUI")
        ASSISTANTUI.resize(1326, 700)
        self.centralwidget = QtWidgets.QWidget(ASSISTANTUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-150, -80, 1561, 951))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("GUI_IMAGES\\3840x2160-black-solid-color-background.jpg"))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(650, 0, 671, 561))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("GUI_IMAGES\Simple Black and White Text Gif.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-30, 0, 661, 341))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("GUI_IMAGES\Title.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 350, 631, 291))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("GUI_IMAGES\TEAM -MEMBER.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(940, 480, 191, 61))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(940, 560, 191, 61))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        ASSISTANTUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(ASSISTANTUI)
        QtCore.QMetaObject.connectSlotsByName(ASSISTANTUI)

    def retranslateUi(self, ASSISTANTUI):
        _translate = QtCore.QCoreApplication.translate
        ASSISTANTUI.setWindowTitle(_translate("ASSISTANTUI", "MainWindow"))
        self.pushButton.setText(_translate("ASSISTANTUI", "START"))
        self.pushButton_2.setText(_translate("ASSISTANTUI", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ASSISTANTUI = QtWidgets.QMainWindow()
    ui = Ui_ASSISTANTUI()
    ui.setupUi(ASSISTANTUI)
    ASSISTANTUI.show()
    sys.exit(app.exec_())
